apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-restapi
  labels:
    app: tekton-restapi
spec:
  selector:
    matchLabels:
      app: tekton-restapi
  template:
    metadata:
      labels:
        app: tekton-restapi
    spec:
      imagePullSecrets:
        - name: dockerhub-mark
      containers:
        - name: tekton-restapi-image
          image: __IMAGE__@__DIGEST__
          ports:
            - name: http-server
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-restapi
  labels:
    app: tekton-restapi
spec:
  ports:
    - port: 9090
      targetPort: http-server
  selector:
    app: tekton-restapi
  type: NodePort